name: wadeema
description:  Flutter Application

publish_to: 'none'

version: 1.0.1


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # firebase messaging
  #Flutter plugin for Firebase Cloud Messaging,
  #  firebase_messaging: ^11.4.0
  #  firebase_core: ^1.5.0

  #A cross platform plugin for displaying and scheduling local notifications
  #  flutter_local_notifications: ^9.9.1

  # Core
  dio: ^4.0.4
  # get lib doesn't update to last version
  get: ^4.6.5
  get_storage: ^2.0.3
  cached_network_image: ^3.2.0
  flutter_bloc: ^8.0.1
  rxdart: ^0.27.3
  cross_file: ^0.3.2
  bloc: ^8.1.2

  # UI
  flutter_screenutil: ^5.5.4
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.8
  pull_to_refresh: ^2.0.0
  #  modal_progress_hud: ^0.1.3
  shimmer: ^2.0.0
  #  fab_circular_menu: ^1.0.2
  #  shadow: ^1.0.0
  #  icon_shadow: ^1.0.1
  #  flutter_staggered_animations: ^1.1.1
  #  flutter_launcher_icons: ^0.9.2
  #  font_awesome_flutter: ^10.2.1
  #  percent_indicator: ^4.0.0
  #  flutter_inner_drawer: ^1.0.0+1
  uuid: ^3.0.5
  #  badges: ^2.0.2
  #  flutter_staggered_grid_view: ^0.4.0
  google_fonts: ^4.0.4
  #  full_screen_image: ^1.0.2
  #  custom_full_image_screen: ^0.0.4
  geolocator: ^9.0.2
  #  photo_view: ^0.13.0
  #  table_calendar: ^3.0.3
  animations: ^2.0.4
  # utils
  #  flutter_share_me: ^1.2.0
  flutter_svg: ^1.0.3
  carousel_slider: ^4.0.0
  #  readmore:
  #    path: lib/custom_libs/readmore-1.0.1
  #  readmore: ^2.1.0
  file_picker: ^5.3.3
  thumbnailer: ^2.0.2
  image_picker: ^0.8.4+5
  #  auto_size_text: ^3.0.0
  #  scroll_snap_list: ^0.7.0
  #  better_player: ^0.0.83
  raygun4flutter: ^2.0.0
  intl: ^0.17.0
  package_info_plus: ^4.1.0

  #  flutter_reaction_button: ^1.0.7+3
  flutter_typeahead: ^4.1.1
  #  supercharged: ^1.12.0
  version: ^2.0.0
  faker: ^2.0.0
  #  hexcolor: ^2.0.0
  flip_card: ^0.6.0
  duration: ^3.0.8
  flutter_easyloading: ^3.0.5
  lottie: ^2.6.0
  # ATTACHMENTS
  #  vcard: ^0.1.1

  #  advance_pdf_viewer: ^2.0.1
  share: ^2.0.4
  #  qr_flutter: ^3.1.0
  #  qr_code_scanner: ^1.0.1
  uploadcare_client: ^4.0.1
  validators:  ^3.0.0
  json_annotation: ^4.4.0
  #  cupertino_icons: 1.0.2
  timeline_tile: ^2.0.0
  #  basic_utils: ^3.0.1
  flutter_progress_hud: ^2.0.0
  visibility_detector: ^0.3.3
  url_launcher: ^6.0.18
  equatable: ^2.0.3
  #  rounded_loading_button: ^2.0.9
  #  flutter_swiper: ^1.1.6
  #  flutter_page_indicator: ^0.0.3
  #  carousel_pro: ^1.0.0
  # FOR PREVIEW LIBRARY
  provider: ^6.0.2
  path_provider: ^2.0.8
  device_frame: ^1.0.0
  #  freezed_annotation: ^0.14.1
  meta: ^1.7.0
  shared_preferences: ^2.0.15
  path: ^1.8.0
  #  collection: ^1.15.0
  #  any_link_preview: ^2.0.6
  #  flutter_link_previewer: ^2.6.2
  #  vs_scrollbar: ^0.2.1
  #  flutter_link_preview:
  #    git: 'https://github.com/ItzNotABug/flutter_link_preview'
  #  syncfusion_flutter_datepicker: ^19.4.47
  #  back_button_interceptor: ^5.0.2
  #  infinite_scroll_pagination: ^3.2.0
  flutter_rating_bar: ^4.0.1

  # XXTEA is a fast and secure encryption algorithm. This is a XXTEA library for Dart.
  xxtea: ^2.1.0

  # An helper to easily exposes a value using InheritedWidget without having to write one.
  sembast: ^3.3.0
  # calculate if location inside polygan or not
  #  maps_toolkit: ^2.0.1
  #  open_file: ^3.2.1
  # convert utm to lat long
  #  utm: ^0.1.3-nullsafety.1
  # check if point is in polygon
  #  point_in_polygon: ^1.0.0
  #This Flutter plugin provides means to perform local, on-device authentication of the user.
  #
  #This means referring to biometric authentication on iOS (Touch ID or lock code)
  # and the fingerprint APIs on Android (introduced in Android 6.0).
  local_auth: ^2.1.2
  flutter_secure_storage: ^6.0.0
  #  pin_code_fields: ^7.4.0
  flutter_udid: ^2.0.0
  google_maps_flutter: ^2.2.3
  location: ^4.3.0
  geocoding: ^2.0.2
  permission_handler: ^8.2.4
  uni_links:
  firebase_core:
  firebase_messaging:
  flutter_keyboard_visibility: ^5.4.1
  introduction_screen: ^3.0.2
  auto_size_text: ^3.0.0
  flutter_statusbarcolor_ns: ^0.5.0
  image: ^3.0.1
  flutter_avif: ^1.4.0
  blur: ^3.1.0
  device_preview: ^1.0.0






dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  # vin_decoder: any
  #   vin_decoder: ^0.1.3
  freezed: ^1.1.1
  analyzer: ^3.2.0
  get_it: ^7.2.0
  smooth_page_indicator: ^1.0.1
  pin_code_fields: ^8.0.1
  flutter_image_compress: ^1.1.3


  # FOR preview library
#  build_runner: ^1.10.2
#  json_serializable: ^3.5.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/wadeema_logo.json

#    flutter pub run build_runner build --delete-conflicting-outputs
#    flutter pub run build_runner watch --delete-conflicting-outputs
