Map<String, String> ar = {
  "unexpected_err": "حصل خطأ غير متوقع",
  "user_cancel_error": "تم الإلغاء من المستخدم",
  "not_found_err": "خطأ : الصفحة مفقودة",
  "unauthorized_err": "خطأ: غير مخول بالوصول",
  "bad_request_err": "الطلب خاطئ",
  "forbidden_err": "خطأ: ممنوع من الوصول, يلزم إعادة تسجيل الدخول",
  "server_err": "حصل خطأ من المخدم",
  "timeout_err": "خطأ : انتهى وقت النفاذ",
  "connection_err": "فشل الاتصال, تأكد من اتصالك بالإنترنت و حاول مجدداً",
  "login": "تسجيل الدخول",
  "register": "تسجيل حساب جديد",
  "email": "الإيميل",
  "password": "كلمة المرور",
  "sign_in": "تسجيل الدخول",
  "forgot_password": "نسيت كلمة المرور؟",
  "reset_password": "إعادة تعيين كلمة المرور",
  "send_otp": "إرسال OTP",
  "verification_code": "رمز التحقق",
  "send_verification": "ارسل رمز التحقق",
  "otp": "OTP",
  "new_here": "جديد هنا؟ قم بالتسجيل",
  "agreement_privacy": "هل توافق على هذه الخصوصية والسياسة؟",
  "send_you_password_reset":
      "نحتاج فقط إلى عنوان بريدك الإلكتروني المسجل لنرسل لك إعادة تعيين كلمة المرور",
  "sign_in_with_phone": "تسجيل الدخول باستخدام الهاتف",
  "login_with_facebook": "تسجيل الدخول باستخدام الفيسبوك",
  "login_with_google": "تسجيل الدخول عبر جوجل",
  "or": "أو",
  "with": "باستخدام",
  "name": "الاسم",
  "user_name": "اسم المستخدم",
  "gender": "الجنس",
  "confirm_password": "تأكيد كلمة المرور",
  "city": "الإمارة",
  "phone_number": "رقم الهاتف",
  "about_me": "تحدث عن نفسي",
  "address": "العنوان",
  "address_ads": "عنوان الإعلان",
  "image": "الصورة الشخصية",
  "search": "بحث",
  "search_in_wadeema": "ابحث في وديمة",
  "view_all": "مشاهدة الكل",
  "are_you_looking_for": "هل تبحث عن",
  "recent_uploaded_items": "الإعلانات التي تم رفعها مؤخراً",
  "most_rate_items": "الإعلانات الأكثر تقييماً",
  "popular_items": "الإعلانات الأكثر شيوعاً",
  "job_ads":"إعلانات التوظيف",
  "change_password": "تغيير كلمة المرور",
  "privacy": "سياسة الخصوصيّة",
  "terms": "الشروط والمصطلحات",
  "faq": "أسئلة مكررة",
  "sign_out": "تسجيل الخروج",
  "set_lang": "اختر اللغة",
  "my_profile": "الملف الشخصي",
  "menu": "القائمة",
  "account_settings": "إعدادت الحساب",
  "edit_profile": "تعديل الملف الشخصي",
  "more": "المزيد",
  "post_left": "Post left",
  "listing": "Listing",
  "following": "متابع",
  "followers": "متابعون",
  "number_of_ads": "عدد الإعلانات",
  "joined_on": "انضم في تاريخ",
  "save": "حفظ",
  "show_email_to_other_user": "إظهار الإيميل للمستخدمين الآخرين",
  "show_phone_number_to_other_user": "إظهار رقم الهاتف للمستخدمين الآخرين.",
  "your_posts": "المنشورات",
  "your_activities": "نشاطاتك",
  "setting_and_privacy": "الإعدادات و الخصوصية",
  "follow": "متابعة",
  "un_follow": "إلغاء المتابعة",
  "ads_list": "قائمة الإعلانات",
  "ads": "إعلان",
  "select_city": "اختر الإمارة",
  "Where_should_we_place_your_ads": "أين يجب أن نضع إعلاناتك؟",
  "place_ads": "أضف إعلانك",
  "what_are_you_listing": "ماذا تسرد؟",
  "choose_the_category_that_your_ad_fits_into": "اختر الفئة التي يناسب إعلانك.",
  "choose_the_right_category_for_your_ad": "اختر الآن الفئة المناسبة لإعلانك:",
  "you_are_almost_there": "انت على وشك الوصول!",
  "include_much_details":
      "قم بتضمين أكبر قدر ممكن من التفاصيل والصور ، وحدد السعر المناسب!",
  "safety_first": "الأمان أولا!",
  "we_review_all_ads":
      "نقوم بمراجعة جميع الإعلانات لنجعل كل شخص على دوبيزل آمنًا وسعيدًا",
  "your_ad_will_not_go_live_if": "لن يتم عرض إعلانك إذا كان:",
  "if_activity_that_violates":
      "لأي عنصر أو نشاط محظور ينتهك قانون دولة الإمارات العربية المتحدة.",
  "if_wrong category": "في فئة خاطئة.",
  "if_multiple_times_or_in_multiple_categories":
      "يتم وضعها عدة مرات ، أو في فئات متعددة.",
  "if_with_fraudulent_or_misleading_information": "بمعلومات احتيالية أو مضللة.",
  "if_located_outside_the_UAE":
      "لعنصر موجود خارج دولة الإمارات العربية المتحدة.",
  "for_more_information_read_our": "لمزيد من المعلومات ، اقرأ لدينا",
  "yes_i_agree": "نعم ، أنا موافق!",
  "next": "التالي",
  "continue": "استمرار",
  "first_name": "الاسم",
  "last_name": "الكنية",
  "block": "حظر",
  "un_block": "إلغاء الحظر",
  "share": "مشاركة",
  "language": "اللغة",
  "profile": "الملف الشخصي",
  "pending_posts": "المنشورات قيد الانتظار ",
  "active_posts": "المنشورات النشطة",
  "favorites": "المفضلة",
  "blocked_users": "قائمة الحظر",
  "chat": "الدردشة",
  "enter_your_message": "أدخل المسج",
  "status": "الحالة",
  "likes": "إعجاب",
  "posted_on": "تم النشر في",
  "since": "منذ",
  "product_description": "تفاصيل الإعلان",
  "please_select_data": "الرجاء اختيار الداتا",
  "see_more": "رؤية المزيد",
  "see_less": "رؤية أقل",
  "sign_in_as_guest": "الدخول ك ضيف",
  "add_advertisement_success": "تم إضافة الإعلان بنجاح",
  "you_should_sign_in": "يجب أن تقوم بتسجيل الدخول أولاً",
  "ok": "نعم",
  "cancel": "إلغاء",
  "rate_user":"تقييم المستخدم",
  "rate_ads":"تقييم الإعلان ",
  "comment":"تعليق",
  "evaluate":"تقييم",
  "title":"الاسم",
  "short_description":"وصف الإعلان",
  "long_description":"الوصف طويل",
  "price":"السعر",
  "add_your_images":"أضف الصور",
  "locate_your_advertisement":"أضف العنوان",
  "selected_location":"حدد عنوانك",
  "user_id":"رقم عضوية المستخدم",
  "about_app":"حول التطبيق",
  "no_items_found":"لا يوجد عناصر",
  "change_notifications_statues":"إيقاف _ تشغيل التنبيهات",
  "dark_mode":"وضع ليلي",
  "just_now":"الآن",
  "second(s) ago":" ثواني",
  "minute(s)":"دقائق",
  "hour(s)":"ساعات",
  "day(s)":"أيام",
  "month(s)":"أشهر",
  "year(s)":"سنوات",
  "this_field_is_required":"هذا الحقل مطلوب",
  "passwords_don't_match":"كلمة السر غير متطابقة",
  "please_fill_all_requirement_data" : "أرجو ملئ كل الداتا المطلوبة",
  "sign_up_success" : "تم تسجيل الحساب بنجاح",
  "notifications" : "التنبيهات",
  "my_favourite" : "المفضلة",
  "send_password" : "لقد أرسلنا كلمة مرور جديدة إلى بريدك الإلكتروني، يرجى التحقق!",
  "back":"الخلف",
  "category":"الفئة",
  "subcategory":"الفئة الفرعية",
  "emirate":"الإمارة",
  "post":"نشر",
  "please_select_category":"يرجى تحديد فئة الإعلان",
  "please_agree_with_terms":"يرجى الموافقة على سياسة الخصوصية",
  "view_results":"عرض النتائج",
  "filter":"فلترة",
  "welcomeToWadeema":"اهلا بك في وديمة",
  "do_not_have_account":"ليس لديك حساب؟",
  "register_now":"سجل الآن",
  "do_have_account":"لديك حساب؟",
  "sign_in_now":"سجل دخول الآن",
  "enter_otp":"ادخل رمز التحقق الذي وصلك عبر رسالة نصية على رقم هاتفك",
  "edit_number":"تعديل الرقم",
  "resend_code":"إعادة إرسال الرمز",
  "verification_has_done":"تمت عملية التحقق من الرمز بنجاح",
  "complete_registration":"إكمال التسجيل",
  "username":"اسم المستخدم",
  "last_search":"عمليات البحث الأخيرة",
  "clear_all":"مسح الكل",
  "select_location":"اختر الموقع",
  "price_not_announced": "السعر غير معلن",
  "gallery": "المعرض",
  "camera": "الكاميرا",
  "first_screen_title":"نرحب بك في تطبيق وديمة الخاص بالإعلانات يمكنك تسجيل برقم موبايل إماراتي أو تجاوز التسجيل و الدخول ضيف للتصفح فقط.",
  "second_screen_title":"تسجيلك في التطبيق و إكمال بروفايلك يمكنك من استخدام جميع الخدمات و الميزات.",
  "third_screen_title":"ابحث عن طلبك بخيارات فلترة متقدمة أو إرفع إعلانك بسهولة. نتمنى لك تجربة مميزة.",
  "skip":"تخطي"
};
