Map<String, String> en = {
  "unexpected_err": "Unexpected error happened",
  "user_cancel_error": "Canceled by the user",
  "not_found_err": "Not found error",
  "unauthorized_err": "Unauthorized error",
  "bad_request_err": "Bad request error",
  "forbidden_err": "Forbidden error",
  "server_err": "Internal server error",
  "timeout_err":
      "Timeout error, it seems your internet connection is poor, Please try again",
  "connection_err":
      "Connection error occurred, please check your internet connection and try again",
  "login": "Login",
  "register": "Register",
  "email": "Email",
  "password": "Password",
  "sign_in": "Sign In",
  "forgot_password": "Forgot password?",
  "reset_password": "Reset password",
  "send_otp": "Send OTP",
  "verification_code": "Verification Code",
  "send_verification": "Send Verification Code",
  "otp": "OTP",
  "new_here": "New here? Sign up",
  "agreement_privacy": "Are you agreement this privacy and policy?",
  "send_you_password_reset":
      "We just need your registered email address to send you password reset",
  "sign_in_with_phone": "Sign In with Phone",
  "login_with_facebook": "Login with Facebook",
  "login_with_google": "Login with Google",
  "or": "OR",
  "with": "With",
  "name": "Name",
  "user_name": "User Name",
  "gender": "Gender",
  "confirm_password": "Confirm Password",
  "city": "City",
  "phone_number": "Phone Number",
  "about_me": "About me",
  "address": "Address",
  "address_ads": "Advertisement title",
  "image": "Image",
  "search": "Search",
  "delete_account":"Delete Account",
  "search_in_wadeema": "Search in Wadeema",
  "view_all": "View All",
  "are_you_looking_for": "Are you looking for",
  "recent_uploaded_items": "Recent Uploaded Items",
  "most_rate_items": "Most Rate Items",
  "popular_items": "Popular Items",
  "job_ads":"Job Ads",
  "change_password": "Change Password",
  "privacy": "Privacy Policy",
  "terms": "Terms & Conditions",
  "faq": "Frequently Asked Questions",
  "sign_out": "Sign Out",
  "set_lang": "Set Language",
  "my_profile": "Profile",
  "menu": "Menu",
  "account_settings": "Account Settings",
  "edit_profile": "Edit Profile",
  "profile": "My profile",
  "more": "More",
  "post_left": "Post left",
  "listing": "Listing",
  "following": "Following",
  "followers": "Followers",
  "number_of_ads": "Number of ads",
  "joined_on": "Joined on",
  "save": "Save",
  "show_email_to_other_user": "Show email to other user.",
  "show_phone_number_to_other_user": "Show phone number to other user.",
  "your_posts": "Your Posts",
  "your_activities": "Your activities",
  "setting_and_privacy": "Setting & Privacy",
  "follow": "Follow",
  "un_follow": "Un Follow",
  "ads_list": "ADS List",
  "ads": "ADS",
  "select_city": "Select a City",
  "Where_should_we_place_your_ads": "Where should we place your ads?",
  "place_ads": "Place an ADS",
  "what_are_you_listing": "What are you listing?",
  "choose_the_category_that_your_ad_fits_into":
      "Choose the category that your ad fits into.",
  "choose_the_right_category_for_your_ad":
      "Now choose the right category for your ad:",
  "you_are_almost_there": "You are almost there!",
  "include_much_details":
      "Include as much details and pictures as possible, and set the right price!",
  "safety_first": "Safety first!",
  "we_review_all_ads":
      "We review all ads to keep everyone on dubizzle safe and happy",
  "your_ad_will_not_go_live_if": "Your ad Will not go live if it is:",
  "if_activity_that_violates":
      "For any prohibited item or activity that violates UAE law.",
  "if_wrong category": "In the wrong category.",
  "if_multiple_times_or_in_multiple_categories":"Placed multiple times, or in multiple categories.",
  "if_with_fraudulent_or_misleading_information":"With fraudulent or misleading information.",
  "if_located_outside_the_UAE":"For an item that is located outside the UAE.",
 "for_more_information_read_our":"For more information, read our",
  "yes_i_agree":"Yes, I agree!",
  "next":"Next",
  "continue":"Continue",
  "first_name":"First Name",
  "last_name":"Last Name",
  "block":"Block",
  "un_block":"Un Block",
  "share":"Share",
  "language":"Language",
  "profile":"Profile",
  "pending_posts":"Pending Posts",
  "active_posts":"Active Posts",
  "favorites":"Favorites",
  "blocked_users":"Blocked Users",
  "chat":"Chat",
  "enter_your_message":"Enter your message",
  "enter_your_post": "Enter your post",
  "status":"Status",
  "likes":"Likes",
  "posted_on":"Posted On",
  "since": "Since",
  "product_description":"Product Description",
  "please_select_data":"Please select data",
  "see_more":"See more",
  "see_less":"See less",
  "sign_in_as_guest":"Sign in as guest",
  "add_advertisement_success":"Add Advertisement Success",
  "you_should_sign_in":"You should sign in success",
  "ok": "OK",
  "cancel": "CANCEL",
  "rate_user":"Rate User",
  "rate_ads":"Rate Ads",
  "comment":"Comment",
  "evaluate":"Evaluate",
  "title":"title",
  "short_description":"Short Description",
  "long_description":"Long Description",
  "price":"Price",
  "add_your_images":"Add your images",
  "locate_your_advertisement":"Locate your advertisement",
  "selected_location":"Selected location",
  "user_id":"User ID",
  "about_app" : "About App",
  "no_items_found":"No Items Found",
  "change_notifications_statues":"Turn on - off notifications",
  "dark_mode":"Dark Mode",
  "just_now":"just now",
  "second(s)":"second(s) ago",
  "minute(s)":"minute(s) ago",
  "hour(s)":"hour(s) ago",
  "day(s)":"day(s) ago",
  "month(s)":"month(s) ago",
  "year(s)":"year(s) ago",
  "this_field_is_required":"This field is required",
  "passwords_don't_match":"Passwords doesn't match",
  "please_fill_all_requirement_data":"Please fill all requirement data",
  "sign_up_success":"Sign up success",
  "notifications":"Notifications",
  "my_favourite":"My Favourite",
  "send_password":"We send a new password to your email, please check!",
  "back":"Back",
  "category": "Category",
  "subcategory":"Subcategory",
  "emirate": "Emirate",
  "post":"Post",
  "please_select_category":"Please select your ad category",
  "please_agree_with_terms":"Please agree with the privacy policy",
  "view_results":"View Results",
  "filter":"Filter",
  "welcomeToWadeema":"Welcome to Wadeema",
  "do_not_have_account": "Don't have account",
  "register_now": "Register Now",
  "do_have_account":"Do have account?",
  "sign_in_now":"Sign in now",
  "enter_otp":"Enter the code sent to your phone number",
  "edit_number":"Edit Number",
  "resend_code":"Resend Code",
  "verification_has_done":"Verification has done",
  "complete_registration":"Complete Registration",
  "username":"Username",
  "last_search":"Search history",
  "clear_all":"Clear All",
  "select_location":"Select location",
  "community":"Community",
  "price_not_announced":"Price not announced",
  "choose_option":"Choose Option",
  "gallery":"Gallery",
  "camera":"Camera",
  "first_screen_title":"نرحب بك في تطبيق وديمة الخاص بالإعلانات يمكنك تسجيل برقم موبايل إماراتي أو تجاوز التسجيل و الدخول ضيف للتصفح فقط.",
  "second_screen_title":"تسجيلك في التطبيق و إكمال بروفايلك يمكنك من استخدام جميع الخدمات و الميزات.",
  "third_screen_title":"ابحث عن طلبك بخيارات فلترة متقدمة أو إرفع إعلانك بسهولة. نتمنى لك تجربة مميزة.",
  "skip":"تخطي"

};
